service: api-hack-diagramas

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  timeout: 30  
  iam:
    role: arn:aws:iam::708642711016:role/LabRole
  stage: dev
  region: us-east-1


functions:
  crearJson:
    handler: functions/CrearJson.lambda_handler
    events:
      - http:
          path: diagramas/crearJson
          method: post
          cors: true
          integration: lambda
  crearEr:
    handler: functions/CrearEr.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:708642711016:layer:eralchemy-layer:3
    events:
      - http:
          path: diagramas/crearEr
          method: post
          cors: true
          integration: lambda
  crearDiagrama:
    handler: functions/CrearArqui.lambda_handler
    environment:
      PATH: "/opt/bin:/var/task:/usr/local/bin:/usr/bin/:/bin"  # Asegura que Lambda encuentre `dot`
      LD_LIBRARY_PATH: "/opt/lib"
    events:
      - http:
          path: diagramas/crearArqui
          method: post
          cors: true
          integration: lambda
  guardarImagen:
    handler: functions/guardarImagen.handler
    events:
      - http:
          path: diagramas/guardarImagen
          method: post
          cors: true

resources:
  Resources:
    BucketDiagramas:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket-diagramas-aws
