service: api-hack-diagramas

frameworkVersion: '3'

provider:
  apiGateway:
    binaryMediaTypes:
      - 'image/png'
      - 'image/jpeg'
  name: aws
  runtime: python3.10
  timeout: 30  
  iam:
    role: arn:aws:iam::708642711016:role/LabRole
  stage: dev
  region: us-east-1


functions:
  crearJson:
    handler: functions/CrearJson.lambda_handler
    events:
      - http:
          path: diagramas/crearJson
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - token
          integration: lambda
  crearEr:
    handler: functions/CrearEr.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:708642711016:layer:eralchemy-layer:3
    events:
      - http:
          path: diagramas/crearEr
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token             
              - token
          integration: lambda
  guardarImagen:
    handler: functions/guardarImagen.lambda_handler
    events:
      - http:
          path: diagramas/guardarImagen
          method: post
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - token
          integration: lambda

resources:
  Resources:
    BucketDiagramas:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket-diagramas-aws
