# .github/workflows/deploy.yml
name: Deploy Python Serverless Services to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy all Python Serverless services
        run: |
          SERVICE_DIRS=(api-usuarios api-productos api-compras)
          DEPLOY_STAGE="dev"

          for service_dir in "${SERVICE_DIRS[@]}"; do
            echo "::group::Deploying service: $service_dir"
            cd "$service_dir"

            # Instala dependencias de Python si existe requirements.txt
            if [ -f "requirements.txt" ]; then
              echo "Installing Python dependencies for $service_dir..."
              pip install -r requirements.txt -t .
            fi

            echo "Deploying $service_dir to AWS (stage: $DEPLOY_STAGE)..."
            sls deploy --stage "$DEPLOY_STAGE" --verbose

            cd ..
            echo "::endgroup::"
          done
