# .github/workflows/deploy.yml
name: Deploy Python Serverless Services to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy all Python Serverless services
        run: |
          DEPLOY_STAGE="dev"

          echo "::group::Deploying api-usuarios"
          cd api-usuarios

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t .
          fi

          sls deploy --stage "$DEPLOY_STAGE" --verbose
          cd ..
          echo "::endgroup::"